apiVersion: apps/v1
kind: Deployment
metadata:
  name: gamingapps
  labels:
    app: gamingapps
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gamingapps
  template:
    metadata:
      labels:
        app: gamingapps
    spec:
      containers:
      - name: gamingapps
        image: lishan2023/gamingapps:replaceImageTag
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: gamingapps-service
spec:
  selector:
    app: gamingapps
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
